#############################################################################
# Makefile for building: DTLib
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sun Apr 22 02:50:31 2018
# Project:  DTLib.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.7.4/bin/qmake -spec /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/delphi/.local/share/data/Nokia/QtCreator/qtc-qmldbg/38922548 -o Makefile DTLib.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.7.4/lib
LIBS          = $(SUBLIBS)    
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.7.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf \
		DTLib.pro
QMAKE_TARGET  = DTLib
DESTDIR       = 
TARGET        = DTLib

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DTLib.pro  /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/delphi/.local/share/data/Nokia/QtCreator/qtc-qmldbg/38922548 -o Makefile DTLib.pro
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/delphi/.local/share/data/Nokia/QtCreator/qtc-qmldbg/38922548 -o Makefile DTLib.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/DTLib1.0.0 || $(MKDIR) .tmp/DTLib1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DTLib1.0.0/ && (cd `dirname .tmp/DTLib1.0.0` && $(TAR) DTLib1.0.0.tar DTLib1.0.0 && $(COMPRESS) DTLib1.0.0.tar) && $(MOVE) `dirname .tmp/DTLib1.0.0`/DTLib1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DTLib1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp SmartPointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

